# Generated by Django 5.2.6 on 2025-10-01 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteCafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('departamento', models.CharField(choices=[('Antioquia', 'Antioquia'), ('Caldas', 'Caldas'), ('Risaralda', 'Risaralda'), ('Quindío', 'Quindío'), ('Valle del Cauca', 'Valle del Cauca'), ('Cundinamarca', 'Cundinamarca'), ('Huila', 'Huila'), ('Tolima', 'Tolima'), ('Cauca', 'Cauca'), ('Nariño', 'Nariño'), ('Santander', 'Santander'), ('Boyacá', 'Boyacá'), ('Otro', 'Otro')], default='Antioquia', max_length=50)),
                ('municipio', models.CharField(max_length=100)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('variedad', models.CharField(choices=[('Caturra', 'Caturra'), ('Castillo', 'Castillo'), ('Bourbon', 'Bourbon'), ('Típica', 'Típica'), ('Maragogipe', 'Maragogipe'), ('Tabí', 'Tabí'), ('Geisha', 'Geisha'), ('Otro', 'Otro')], default='Castillo', max_length=20)),
                ('hectareas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nivel_sombra', models.CharField(choices=[('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo')], default='Medio', max_length=10)),
                ('altitud', models.PositiveIntegerField()),
                ('arboles_hectarea', models.PositiveIntegerField(default=5000)),
                ('edad_plantacion', models.PositiveIntegerField(default=2)),
                ('fecha_siembra', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lotes_cafe',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
