# Generated by Django 5.2.7 on 2025-10-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmbralRadiacionSolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variedad', models.CharField(choices=[('Caturra', 'Caturra'), ('Castillo', 'Castillo'), ('Bourbon', 'Bourbon'), ('Típica', 'Típica'), ('Maragogipe', 'Maragogipe'), ('Tabí', 'Tabí'), ('Geisha', 'Geisha'), ('Otro', 'Otro')], help_text='Variedad de café', max_length=20, unique=True)),
                ('radiacion_minima', models.DecimalField(decimal_places=2, help_text='Radiación solar mínima óptima (W/m²)', max_digits=6)),
                ('radiacion_optima', models.DecimalField(decimal_places=2, help_text='Radiación solar óptima (W/m²)', max_digits=6)),
                ('radiacion_maxima', models.DecimalField(decimal_places=2, help_text='Radiación solar máxima aceptable (W/m²)', max_digits=6)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de características especiales')),
                ('nivel_sombra_recomendado', models.CharField(choices=[('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo')], default='Medio', help_text='Nivel de sombra recomendado para esta variedad', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Umbral de Radiación Solar',
                'verbose_name_plural': 'Umbrales de Radiación Solar',
                'db_table': 'cultivos_umbral_radiacion',
            },
        ),
    ]
