# Generated by Django 5.2.7 on 2025-10-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0002_umbralradiacionsolar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotecafe',
            name='altitud',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='umbralradiacionsolar',
            name='radiacion_maxima',
            field=models.DecimalField(decimal_places=2, help_text='Radiación solar máxima aceptable (W/m²)', max_digits=7),
        ),
        migrations.AlterField(
            model_name='umbralradiacionsolar',
            name='radiacion_minima',
            field=models.DecimalField(decimal_places=2, help_text='Radiación solar mínima óptima (W/m²)', max_digits=7),
        ),
        migrations.AlterField(
            model_name='umbralradiacionsolar',
            name='radiacion_optima',
            field=models.DecimalField(decimal_places=2, help_text='Radiación solar óptima (W/m²)', max_digits=7),
        ),
    ]
