# Generated by Django 5.2.7 on 2025-10-16 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0002_load_umbrales_radiacion'),
        ('cultivos', '0003_alter_lotecafe_altitud_and_more'),
    ]

    operations = [
    ]
