# Generated by Django 5.2.7 on 2025-10-16 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0006_round_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotecafe',
            name='municipio',
        ),
    ]
