# Generated by Django 5.2.6 on 2025-11-07 20:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cultivos', '0007_remove_lotecafe_municipio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPrediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_historicos_minimos', models.IntegerField(default=30, help_text='Mínimo de días históricos necesarios para predicir')),
                ('dias_historicos_recomendados', models.IntegerField(default=90, help_text='Días históricos recomendados para mejor precisión')),
                ('confianza_minima_alerta', models.DecimalField(decimal_places=2, default=70.0, help_text='Confianza mínima para generar alertas (%)', max_digits=5)),
                ('reentrenar_cada_dias', models.IntegerField(default=7, help_text='Re-entrenar modelos cada X días')),
                ('max_error_aceptable', models.DecimalField(decimal_places=2, default=15.0, help_text='Error máximo aceptable antes de re-entrenar (%)', max_digits=6)),
                ('generar_predicciones_automaticas', models.BooleanField(default=True, help_text='Generar predicciones automáticamente')),
                ('hora_generacion_automatica', models.TimeField(default='06:00:00', help_text='Hora para generar predicciones automáticas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Predicciones',
                'verbose_name_plural': 'Configuraciones de Predicciones',
                'db_table': 'configuracion_predicciones',
            },
        ),
        migrations.CreateModel(
            name='PrediccionRadiacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prediccion', models.CharField(choices=[('1_dia', '1 día'), ('3_dias', '3 días'), ('7_dias', '7 días')], default='3_dias', max_length=10)),
                ('metodo_utilizado', models.CharField(choices=[('linear_regression', 'Regresión Lineal'), ('random_forest', 'Random Forest'), ('arima', 'ARIMA'), ('ensemble', 'Conjunto de Modelos')], default='random_forest', max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('radiacion_actual', models.DecimalField(decimal_places=2, help_text='Radiación actual en W/m²', max_digits=7)),
                ('temperatura_actual', models.DecimalField(decimal_places=2, help_text='Temperatura actual en °C', max_digits=5)),
                ('humedad_actual', models.DecimalField(decimal_places=2, help_text='Humedad actual en %', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('radiacion_predicha', models.JSONField(help_text='Array con predicciones: [día1, día2, ...]')),
                ('confianza_prediccion', models.DecimalField(decimal_places=2, help_text='Nivel de confianza de la predicción (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('datos_historicos_usados', models.IntegerField(help_text='Cantidad de días históricos utilizados')),
                ('r2_score', models.DecimalField(blank=True, decimal_places=4, help_text='R² del modelo utilizado', max_digits=5, null=True)),
                ('mae_score', models.DecimalField(blank=True, decimal_places=4, help_text='Error Absoluto Medio', max_digits=8, null=True)),
                ('alerta_generada', models.BooleanField(default=False, help_text='Si se generó alerta por radiación peligrosa')),
                ('nivel_riesgo_predicho', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Crítico')], default='medio', max_length=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='cultivos.lotecafe')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Predicción de Radiación Solar',
                'verbose_name_plural': 'Predicciones de Radiación Solar',
                'db_table': 'predicciones_radiacion',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPrediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_verificacion', models.DateField(help_text='Fecha en que se verificó la predicción')),
                ('radiacion_real', models.DecimalField(decimal_places=2, help_text='Radiación real observada en W/m²', max_digits=7)),
                ('radiacion_predicha', models.DecimalField(decimal_places=2, help_text='Radiación que se había predicho en W/m²', max_digits=7)),
                ('error_absoluto', models.DecimalField(decimal_places=2, help_text='Error absoluto |real - predicho|', max_digits=7)),
                ('error_porcentual', models.DecimalField(decimal_places=2, help_text='Error porcentual', max_digits=6)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('prediccion_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precision', to='predicciones.prediccionradiacion')),
            ],
            options={
                'verbose_name': 'Historial de Precisión',
                'verbose_name_plural': 'Historial de Precisiones',
                'db_table': 'historial_precision_predicciones',
            },
        ),
        migrations.AddIndex(
            model_name='prediccionradiacion',
            index=models.Index(fields=['lote', 'fecha_generacion'], name='prediccione_lote_id_3a6eb8_idx'),
        ),
        migrations.AddIndex(
            model_name='prediccionradiacion',
            index=models.Index(fields=['usuario', 'fecha_generacion'], name='prediccione_usuario_ae850b_idx'),
        ),
        migrations.AddIndex(
            model_name='prediccionradiacion',
            index=models.Index(fields=['tipo_prediccion'], name='prediccione_tipo_pr_d83c38_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='historialprediccion',
            unique_together={('prediccion_original', 'fecha_verificacion')},
        ),
    ]
