# Generated by Django 5.2.6 on 2025-10-03 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cultivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosClimaticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_medicion', models.DateTimeField(help_text='Fecha real de la medición')),
                ('irradiancia_solar', models.DecimalField(decimal_places=2, help_text='Irradiancia solar global (GHI) en W/m²', max_digits=8)),
                ('temperatura', models.DecimalField(decimal_places=2, help_text='Temperatura ambiente en °C', max_digits=5)),
                ('humedad_relativa', models.DecimalField(decimal_places=2, help_text='Humedad relativa en %', max_digits=5)),
                ('nubosidad', models.DecimalField(blank=True, decimal_places=2, help_text='Nubosidad en %', max_digits=5, null=True)),
                ('precipitacion', models.DecimalField(blank=True, decimal_places=2, help_text='Precipitación en mm', max_digits=6, null=True)),
                ('presion_atmosferica', models.DecimalField(blank=True, decimal_places=2, help_text='Presión atmosférica en hPa', max_digits=6, null=True)),
                ('velocidad_viento', models.DecimalField(blank=True, decimal_places=2, help_text='Velocidad del viento en m/s', max_digits=5, null=True)),
                ('fuente_datos', models.CharField(choices=[('openweather', 'OpenWeather Map'), ('nasa_power', 'NASA POWER'), ('ideam', 'IDEAM Colombia'), ('sensor_iot', 'Sensor IoT Local'), ('manual', 'Ingreso Manual')], default='openweather', max_length=20)),
                ('calidad_datos', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_climaticos', to='cultivos.lotecafe')),
            ],
            options={
                'verbose_name': 'Dato Climático',
                'verbose_name_plural': 'Datos Climáticos',
                'db_table': 'clima_datos_climaticos',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['lote', 'fecha_registro'], name='clima_datos_lote_id_46a1c7_idx'), models.Index(fields=['fecha_medicion'], name='clima_datos_fecha_m_358735_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricoClimatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('temp_promedio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temp_maxima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temp_minima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humedad_promedio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('irradiancia_promedio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precipitacion_acumulada', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_climatico', to='cultivos.lotecafe')),
            ],
            options={
                'db_table': 'clima_historico',
                'indexes': [models.Index(fields=['lote', 'fecha'], name='clima_histo_lote_id_2cc0e9_idx')],
                'unique_together': {('lote', 'fecha')},
            },
        ),
    ]
