# Generated by Django 5.2.7 on 2025-10-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosclimaticos',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Ciudad donde se realizó la medición', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datosclimaticos',
            name='descripcion_clima',
            field=models.CharField(blank=True, help_text='Descripción del clima (ej: nubes, lluvia)', max_length=100, null=True),
        ),
    ]
