# Generated by Django 5.2.7 on 2025-10-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0002_datosclimaticos_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosclimaticos',
            name='fuente_datos',
            field=models.CharField(choices=[('openweather', 'OpenWeather Map'), ('open_meteo', 'Open-Meteo (Gratuita)'), ('nasa_power', 'NASA POWER'), ('ideam', 'IDEAM Colombia'), ('sensor_iot', 'Sensor IoT Local'), ('manual', 'Ingreso Manual')], default='openweather', max_length=20),
        ),
    ]
