# Generated by Django 5.2.6 on 2025-10-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0003_alter_datosclimaticos_fuente_datos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosclimaticos',
            name='fuente_datos',
            field=models.CharField(choices=[('open_meteo', 'Open-Meteo'), ('manual', 'Ingreso Manual')], default='open_meteo', max_length=20),
        ),
    ]
