# Generated by Django 5.2.6 on 2025-10-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0004_alter_datosclimaticos_fuente_datos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosclimaticos',
            name='fuente_datos',
            field=models.CharField(choices=[('nasa_power', 'NASA POWER'), ('manual', 'Ingreso Manual')], default='nasa_power', max_length=20),
        ),
    ]
